export const Questions = [
  {
    id: 1,
    prompt: "What's the biggest animal in the world?",
    optionA: 'Elephant',
    optionB: 'Ostrich',
    optionC: 'Blue Whale',
    optionD: 'Saltwater Crocodile',
    answer: 'C',
  },
  {
    id: 2,
    prompt: 'Who painted Mona Lisa?',
    optionA: 'Michelangelo',
    optionB: 'Leonardo da Vinci',
    optionC: 'Vincent Van Gogh',
    optionD: 'Salvador Dali',
    answer: 'B',
  },
  {
    id: 3,
    prompt: 'Which planet is closest to the sun?',
    optionA: 'Venus',
    optionB: 'Mars',
    optionC: 'Saturn',
    optionD: 'Mercury',
    answer: 'D',
  },
  {
    id: 4,
    prompt: 'What is the largest country in the world?',
    optionA: 'Russia',
    optionB: 'USA',
    optionC: 'China',
    optionD: 'Australia',
    answer: 'A',
  },
  {
    id: 5,
    prompt: 'How many elements are there in the periodic table?',
    optionA: '87',
    optionB: '92',
    optionC: '123',
    optionD: '118',
    answer: 'D',
  },
  {
    id: 6,
    prompt: 'What does He stand for on the periodic table?',
    optionA: 'Helium',
    optionB: 'Hassium',
    optionC: 'Xenon',
    optionD: 'Ruthenium',
    answer: 'A',
  },
  {
    id: 7,
    prompt: 'How many sides does a heptadecagon have?',
    optionA: 'Ten',
    optionB: 'Thirteen',
    optionC: 'Seventeen',
    optionD: 'Nine',
    answer: 'C',
  },
  {
    id: 8,
    prompt: 'What star sign would someone born on August 24th be?',
    optionA: 'Leo',
    optionB: 'Scorpio',
    optionC: 'Virgo',
    optionD: 'Taurus',
    answer: 'C',
  },
  {
    id: 9,
    prompt: 'What is the smallest country in the world?',
    optionA: 'Vatican City',
    optionB: 'Monaco',
    optionC: 'Maldives',
    optionD: 'Panama',
    answer: 'A',
  },
]
